### ISSUE TITLE
Is there any way to directly access the raw Goal.com data?

### ISSUE THREAD

**Issue by AlexanderTekle** [bcbi-edu/p_eickhoff_SOCCER#1]
Hey folks, I wanted to play with this dataset a bit. I'm having some trouble working with Chrome/Chromedriver as I'm on a virtual machine without UI and am running into some various errors.

Was just wondering if there was anyway to get access to the raw dataset, maybe a downloadable version?

Thanks!

**Comment by yakazimir** [comment]
Was this resolved? I am also having issues with the chromedriver .
